### ISSUE TITLE
__init__.py file points to missing biopython module

### ISSUE THREAD

**Issue by nguyenvanessa** [jbloomlab/dms_tools2#50] opened 2020-10-07 22:50 UTC
Hi Jesse,

When I try to import dms_tools2 into my Jupyter Notebook, I get an error: "'Bio.Seq' has no attribute 'IUPAC'".

The error occurs on line 55 of /dms_tools2/__init__.py. It looks like Biopython has moved ambiguous_dna_values to Bio.Data.IUPACData.ambiguous_DNA_values. 

Changing this allowed me to import dms_tools2

**Comment by jbloom** [comment] 2020-10-07 22:59
@nguyenvanessa, thanks for finding this. Do you want to make a pull request fixing it in code? Otherwise I can do it as well.

**Comment by nguyenvanessa** [comment] 2020-10-08 00:01
I've made a pull request fixing this

**Comment by jbloom** [comment] 2020-10-11 13:29
Merged in #51 and fixed in version 2.6.7. The cause of the issue was that the newest biopython (1.78) deprecated `Bio.Seq.IUPAC`.

**Closed by jbloom** 2020-10-11 13:29 UTC
